package co.edu.unicauca.trabajofinalbases2.presentation;

import co.edu.unicauca.trabajofinalbases2.domain.ArbolBMas;
import co.edu.unicauca.trabajofinalbases2.utilities.Archivo;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class Interfaz extends javax.swing.JFrame {

    private Archivo arc;
    private String ruta;
    private List<String> ListDatos;
    private ArbolBMas<Integer> arbol;

    /**
     * Creates new form Interfaz
     */
    public Interfaz(int n) {
        initComponents();
        this.arc = new Archivo();
        this.ruta = "datos.txt";
        this.arbol = new ArbolBMas<>(4);
        crearArchivo(n);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        txtGenerar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIngresoValor = new javax.swing.JTextField();
        txtIngresoCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarCodigo = new javax.swing.JTextField();
        btnBuscarIndexada = new javax.swing.JButton();
        btnBuscarNoIndexada = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtGenerar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGenerarKeyTyped(evt);
            }
        });

        jLabel6.setText("Genear Registros");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(txtGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnGenerar)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnGenerar)
                .addGap(94, 94, 94))
        );

        jTabbedPane3.addTab("Generar", jPanel3);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("AGREGAR VALORES");

        jLabel2.setText("Codigo Unico:");

        jLabel3.setText("Valor Asociado");

        txtIngresoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresoValorKeyTyped(evt);
            }
        });

        txtIngresoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresoCodigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIngresoCodigo)
                    .addComponent(txtIngresoValor))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIngresoCodigo)
                        .addGap(29, 29, 29)
                        .addComponent(txtIngresoValor)))
                .addGap(29, 29, 29)
                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        jLabel2.getAccessibleContext().setAccessibleName("agregarProd");
        jLabel3.getAccessibleContext().setAccessibleName("PrecioProducto");

        jTabbedPane3.addTab("Agregar", jPanel1);

        jLabel4.setText("BUSCAR ");

        jLabel5.setText("Ingrese Codigo");

        txtBuscarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarCodigoKeyTyped(evt);
            }
        });

        btnBuscarIndexada.setText("BusquedaIndexada");
        btnBuscarIndexada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIndexadaActionPerformed(evt);
            }
        });

        btnBuscarNoIndexada.setText("BusquedaNoIndexada");
        btnBuscarNoIndexada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNoIndexadaActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnBuscarIndexada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBuscarCodigo)
                        .addGap(76, 76, 76))
                    .addComponent(btnBuscarNoIndexada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(192, 192, 192))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarNoIndexada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarIndexada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Buscar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarNoIndexadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNoIndexadaActionPerformed
        int idBuscar = Integer.parseInt(txtBuscarCodigo.getText());
        long tiempoInicio, tiempoFinal, tiempoTotal;

        tiempoInicio = System.currentTimeMillis();

        String linea = arc.leerLineaPorDato(ruta, idBuscar);

        tiempoFinal = System.currentTimeMillis();
        tiempoTotal = tiempoFinal - tiempoInicio;

        if (linea.equalsIgnoreCase("El dato no se encuentra en el archivo")) {
            JOptionPane.showMessageDialog(jTabbedPane3, "EL dato " + idBuscar + " no se encuentra\n"
                    + " TIEMPO DE SALIDA DE LA BUSQUEDA NO INDEXADA ES: " + tiempoTotal + " milisegundos", "No Found", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, linea
                    + " TIEMPO DE SALIDA DE LA BUSQUEDA NO INDEXADA ES: " + tiempoTotal + " milisegundos");
        }
    }//GEN-LAST:event_btnBuscarNoIndexadaActionPerformed

    private void btnBuscarIndexadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIndexadaActionPerformed
        int codigoBuscar = Integer.parseInt(txtBuscarCodigo.getText());
        long tiempoInicio, tiempoFinal, tiempoTotal;

        tiempoInicio = System.currentTimeMillis();

        int posicion = arbol.estaBMas(codigoBuscar);

        tiempoFinal = System.currentTimeMillis();
        tiempoTotal = tiempoFinal - tiempoInicio;
        if (posicion >= 0) {
            JOptionPane.showMessageDialog(rootPane, "El dato " + codigoBuscar + " esta en la posicion " + (posicion + 1) + " del arbol\n"
                    + " TIEMPO DE SALIDA DE LA BUSQUEDA INDEXADA ES: " + tiempoTotal + " milisegundos");
        } else {
            JOptionPane.showMessageDialog(jTabbedPane3, "EL dato " + codigoBuscar + " no se encuentra\n"
                    + " TIEMPO DE SALIDA DE LA BUSQUEDA INDEXADA ES: " + tiempoTotal + " milisegundos", "No Found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarIndexadaActionPerformed

    private void txtBuscarCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCodigoKeyTyped
        validaIngresoNumeros(evt);
    }//GEN-LAST:event_txtBuscarCodigoKeyTyped

    private void txtIngresoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoCodigoKeyTyped
        validaIngresoNumeros(evt);
    }//GEN-LAST:event_txtIngresoCodigoKeyTyped

    private void txtIngresoValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresoValorKeyTyped
        validaIngresoNumeros(evt);
    }//GEN-LAST:event_txtIngresoValorKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int codigo = Integer.parseInt(txtIngresoCodigo.getText());
        int valor = Integer.parseInt(txtIngresoValor.getText());
        boolean validar = true;

        if (validaIdUnico(codigo)) {
            if (codigo < 1 || codigo > 1000000) {
                JOptionPane.showMessageDialog(jTabbedPane3, "El codigo debe ser un número entero entre 1 y 1000000,",
                        "Error de ingreso", JOptionPane.ERROR_MESSAGE);
                validar = false;
            }
            if (valor < 1 || valor > 1000000) {
                JOptionPane.showMessageDialog(jTabbedPane3, "El valor debe ser un número entero entre 1 y 1000000,",
                        "Error de ingreso", JOptionPane.ERROR_MESSAGE);
                validar = false;
            }

            if (validar) {
                this.arc.escribir(ruta, codigo + " " + valor);
                JOptionPane.showMessageDialog(rootPane, "Se registraron valores correctamente");
                txtIngresoCodigo.setText("");
                txtIngresoValor.setText("");
                cargarArbol();
            }
        } else {
            JOptionPane.showMessageDialog(jTabbedPane3, "El codigo ya existe,",
                    "codigo duplicado", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtGenerarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenerarKeyTyped
        validaIngresoNumeros(evt);
    }//GEN-LAST:event_txtGenerarKeyTyped

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        
        int numRegistro = Integer.parseInt(txtGenerar.getText());

        if (numRegistro < 1) {
            JOptionPane.showMessageDialog(jTabbedPane3, "No se puede generar 0 Registros,",
                    "Error de Registro", JOptionPane.ERROR_MESSAGE);
           
        }else{
            this.arc.eliminarArchivo(ruta);
            crearArchivo(numRegistro);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void validaIngresoNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }

    private boolean validaIdUnico(int id) {
        boolean validarId = true;
        actualizarLista();
        for (String dato : ListDatos) {
            String[] dat = dato.split(" ");
            if (id == Integer.parseInt(dat[0])) {
                validarId = false;
                break;
            }
        }
        return validarId;
    }

    private void actualizarLista() {
        ListDatos = arc.leer(ruta);
    }

    private void cargarArbol() {
        actualizarLista();
        String[] dat = null;
        for (String list : ListDatos) {
            dat = list.split(" ");
            arbol.insertar(Integer.parseInt(dat[0]));
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarIndexada;
    private javax.swing.JButton btnBuscarNoIndexada;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField txtBuscarCodigo;
    private javax.swing.JTextField txtGenerar;
    private javax.swing.JTextField txtIngresoCodigo;
    private javax.swing.JTextField txtIngresoValor;
    // End of variables declaration//GEN-END:variables

    private void crearArchivo(int n) {

        if (n > 0) {
            int[] claves = null;
            int[] valores = null;

            valores = ThreadLocalRandom.current().ints(1, 1000000).limit(n).toArray();

            claves = (ThreadLocalRandom.current().ints(1, 1000000).distinct().limit(n).toArray());
            for (int i = 0; i < claves.length; i++) {
                this.arc.escribir(ruta, claves[i] + " " + valores[i]);
            }
            JOptionPane.showMessageDialog(null, "Carga exitosa: ");
            
        }

        cargarArbol();
    }
    
    
}
